name: run-tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Run sbt test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SBT Action
        uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: test